version: '3.8'

services:
  # Override for development
  mongodb:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blogapp_dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8000
      MONGO_URI: mongodb://admin:password@mongodb:27017/blogapp_dev?authSource=admin
      JWT_SECRET: dev-jwt-secret-key
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./backend/uploads:/app/uploads
      - ./backend/gcp_key.json:/app/gcp_key.json:ro
    command: npm run dev
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_API_URL: http://localhost:8000/api
    command: npm start

  # Remove proxy for development - direct access to services
  proxy:
    profiles:
      - disabled