# nixpacks.toml
# Railway build configuration

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = [
    "npm install --prefix backend",
    "npm install --prefix frontend"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"